"""delete fav number

Revision ID: 4a900061f6ce
Revises: 79bb629c8875
Create Date: 2024-11-21 13:53:48.111085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4a900061f6ce'
down_revision: Union[str, None] = '79bb629c8875'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'fav_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fav_number', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
