"""Description of changes

Revision ID: 79bb629c8875
Revises: e7cb9cf27879
Create Date: 2024-11-21 13:51:29.636744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79bb629c8875'
down_revision: Union[str, None] = 'e7cb9cf27879'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fav_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'fav_number')
    # ### end Alembic commands ###
